DROP TABLE Produto;

CREATE TABLE "PRODUTO" (
	"COD_GTIN"	INTEGER NOT NULL,
	"DAT_EMISSAO"	TEXT NOT NULL,
	"COD_TIPO_PAGAMENTO"	INTEGER NOT NULL,
	"COD_PRODUTO"	INTEGER NOT NULL,
	"COD_NCM"	INTEGER NOT NULL,
	"COD_UNIDADE"	TEXT,
	"DSC_PRODUTO"	TEXT,
	"VLR_UNITARIO"	TEXT NOT NULL,
	"ID_ESTABELECIMENTO"	INTEGER NOT NULL,
	"NME_ESTABELECIMENTO"	TEXT,
	"NME_LOGRADOURO"	TEXT,
	"COD_NUMERO_LOGRADOURO"	INTEGER NOT NULL,
	"NME_COMPLEMENTO"	TEXT,
	"NME_BAIRRO"	TEXT,
	"COD_MUNICIPIO_IBGE"	INTEGER NOT NULL,
	"NME_MUNICIPIO"	TEXT,
	"NME_SIGLA_UF"	TEXT,
	"COD_CEP"	INTEGER NOT NULL,
	"NUM_LATITUDE"	TEXT,
	"NUM_LONGITUDE"	TEXT
);

.mode csv
.import Produto.csv Produto