DROP TABLE IF EXISTS "PRODUTO";

CREATE TABLE "PRODUTO" (
	"PRODUTO_ID"	INTEGER NOT NULL,
	"COD_GTIN"	INTEGER NOT NULL,
	"DAT_EMISSAO"	TEXT NOT NULL,
	"COD_TIPO_PAGAMENTO"	INTEGER NOT NULL,
	"COD_PRODUTO"	INTEGER NOT NULL,
	"COD_NCM"	INTEGER NOT NULL,
	"COD_UNIDADE"	TEXT,
	"DSC_PRODUTO"	TEXT,
	"VLR_UNITARIO"	TEXT NOT NULL,
	"ID_ESTABELECIMENTO"	INTEGER NOT NULL,
	"NME_ESTABELECIMENTO"	TEXT,
	"NME_LOGRADOURO"	TEXT,
	"COD_NUMERO_LOGRADOURO"	INTEGER NOT NULL,
	"NME_COMPLEMENTO"	TEXT,
	"NME_BAIRRO"	TEXT,
	"COD_MUNICIPIO_IBGE"	INTEGER NOT NULL,
	"NME_MUNICIPIO"	TEXT,
	"NME_SIGLA_UF"	TEXT,
	"COD_CEP"	INTEGER NOT NULL,
	"NUM_LATITUDE"	TEXT,
	"NUM_LONGITUDE"	TEXT,
	PRIMARY KEY("PRODUTO_ID")
);

INSERT INTO PRODUTO  VALUES (2,1,'10/10/10',1,1,1,'1','ABC','1.99',1,'ASB','ASS',1,'SAEA','BAIRO',
12,'ADFRG','ES',2324,'FKJDFDKJ','FJROIJE');

